### ISSUE TITLE
Mod Crashes(PC)

### ISSUE THREAD

**Issue by Hot-Sausage07** [pixaxeofpixie/Braindustry-Mod#51]
breh jpeg pixmap error XD

**Comment by pixaxeofpixie** [comment]
Crashlog/laat log pls

**Comment by pixaxeofpixie** [comment]
where

**Comment by uujuju1** [comment]
Mindustry has crashed. How unfortunate.
Version: release build 126.2
OS: Windows 7 x32
Java Version: 1.8.0_201-1-ojdkbuild
Java Architecture: 32
1 Mods: betamindy:0.9
[#b59e72]Demo of Chaos Itself[]

arc.util.ArcRuntimeException: Error loading pixmap.
	at arc.graphics.Pixmap$NativePixmap.<init>(Pixmap.java:611)
	at arc.graphics.Pixmap.<init>(Pixmap.java:53)
	at mindustry.core.Renderer.takeMapScreenshot(Renderer.java:344)
	at mindustry.core.Control.update(Control.java:552)
	at arc.ApplicationCore.update(ApplicationCore.java:36)
	at mindustry.ClientLauncher.update(ClientLauncher.java:164)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
 that is my crash log

**Comment by pixaxeofpixie** [comment]
Fixed in next build wait new release
