### ISSUE TITLE
mod does not run on server

### ISSUE THREAD

**Issue by Fatonndev** [pixaxeofpixie/Braindustry-Mod#86]
The mod does not run on server.

[11-07 16:29:44] [E] java.lang.NullPointerException: Cannot read field "input" because "mindustry.Vars.control" is null
        at braindustry.BraindustryMod.lambda$new$0(BraindustryMod.java:39)
        at arc.struct.Seq.each(Seq.java:199)
        at braindustry.ModListener.update(ModListener.java:45)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:88)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:53)

**Comment by Zelaux** [comment]
Fixed
